services:
  db:
    image: postgres:17
    container_name: db-wb  
    networks:
      - backend
    environment:
      POSTGRES_DB: dbpostgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  backend:
    driver: bridge  

volumes:
  backend-node-modules: {}
  postgres_data: {}
